/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motoconnect;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author PC
 */
public class Tela_Lista_Encomendas extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Lista_Encomendas
     */
    public Tela_Lista_Encomendas() {
        initComponents();
    }
    
    private Connection getConnection() throws SQLException {
        String url = "jdbc:mysql://localhost:3306/mysql";
        String user = "root";
        String password = "";
        return DriverManager.getConnection(url, user, password);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPNfundo10 = new javax.swing.JPanel();
        JPNlista10 = new javax.swing.JPanel();
        JLBlista10 = new javax.swing.JLabel();
        JSPtabela10 = new javax.swing.JScrollPane();
        JTBtabela10 = new javax.swing.JTable();
        JTBatualizar10 = new javax.swing.JButton();
        JTBvoltar10 = new javax.swing.JButton();
        JPNtabelaencomenda10 = new javax.swing.JPanel();
        JLBtabelaencomenda10 = new javax.swing.JLabel();
        JLBmotoconnect10 = new javax.swing.JLabel();
        JTFnumero10 = new javax.swing.JTextField();
        JTForigem10 = new javax.swing.JTextField();
        JTFentragador10 = new javax.swing.JTextField();
        JTFdestino10 = new javax.swing.JTextField();
        JTFdata10 = new javax.swing.JTextField();
        JTFstatus10 = new javax.swing.JTextField();
        JLBnumero10 = new javax.swing.JLabel();
        JLBorigem10 = new javax.swing.JLabel();
        JLBentragador10 = new javax.swing.JLabel();
        JLBdestino10 = new javax.swing.JLabel();
        JLBdata10 = new javax.swing.JLabel();
        JLBstatus10 = new javax.swing.JLabel();
        JTBexcluir10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPNfundo10.setBackground(new java.awt.Color(0, 0, 204));
        JPNfundo10.setPreferredSize(new java.awt.Dimension(1000, 600));

        JPNlista10.setBackground(new java.awt.Color(0, 102, 255));
        JPNlista10.setPreferredSize(new java.awt.Dimension(844, 30));

        JLBlista10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLBlista10.setForeground(new java.awt.Color(255, 255, 255));
        JLBlista10.setText("Lista de encomendas");

        javax.swing.GroupLayout JPNlista10Layout = new javax.swing.GroupLayout(JPNlista10);
        JPNlista10.setLayout(JPNlista10Layout);
        JPNlista10Layout.setHorizontalGroup(
            JPNlista10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNlista10Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(JLBlista10)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        JPNlista10Layout.setVerticalGroup(
            JPNlista10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNlista10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBlista10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        JTBtabela10.setBackground(new java.awt.Color(255, 51, 51));
        JTBtabela10.setForeground(new java.awt.Color(255, 255, 255));
        JTBtabela10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "numero_pedido", "endereco_origem", "nome_entregador", "endereco_destino", "data_entrega", "statuss"
            }
        ));
        JTBtabela10.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JTBtabela10AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        JSPtabela10.setViewportView(JTBtabela10);

        JTBatualizar10.setBackground(new java.awt.Color(255, 51, 51));
        JTBatualizar10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JTBatualizar10.setForeground(new java.awt.Color(255, 255, 255));
        JTBatualizar10.setText("ATUALIZAR STATUS");
        JTBatualizar10.setMaximumSize(new java.awt.Dimension(106, 25));
        JTBatualizar10.setPreferredSize(new java.awt.Dimension(106, 25));
        JTBatualizar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBatualizar10ActionPerformed(evt);
            }
        });

        JTBvoltar10.setBackground(new java.awt.Color(255, 51, 51));
        JTBvoltar10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JTBvoltar10.setForeground(new java.awt.Color(255, 255, 255));
        JTBvoltar10.setText("VOLTAR");
        JTBvoltar10.setMaximumSize(new java.awt.Dimension(106, 25));
        JTBvoltar10.setPreferredSize(new java.awt.Dimension(106, 25));
        JTBvoltar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBvoltar10ActionPerformed(evt);
            }
        });

        JPNtabelaencomenda10.setBackground(new java.awt.Color(255, 0, 51));

        JLBtabelaencomenda10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLBtabelaencomenda10.setForeground(new java.awt.Color(255, 255, 255));
        JLBtabelaencomenda10.setText("Tabela encomendas");

        javax.swing.GroupLayout JPNtabelaencomenda10Layout = new javax.swing.GroupLayout(JPNtabelaencomenda10);
        JPNtabelaencomenda10.setLayout(JPNtabelaencomenda10Layout);
        JPNtabelaencomenda10Layout.setHorizontalGroup(
            JPNtabelaencomenda10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNtabelaencomenda10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBtabelaencomenda10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPNtabelaencomenda10Layout.setVerticalGroup(
            JPNtabelaencomenda10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNtabelaencomenda10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBtabelaencomenda10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JLBmotoconnect10.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\MotoConnect_Projeto\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\motoqueiro.png")); // NOI18N

        JTFnumero10.setBackground(new java.awt.Color(204, 204, 204));

        JTForigem10.setBackground(new java.awt.Color(204, 204, 204));

        JTFentragador10.setBackground(new java.awt.Color(204, 204, 204));

        JTFdestino10.setBackground(new java.awt.Color(204, 204, 204));

        JTFdata10.setBackground(new java.awt.Color(204, 204, 204));

        JTFstatus10.setBackground(new java.awt.Color(204, 204, 204));

        JLBnumero10.setForeground(new java.awt.Color(255, 255, 255));
        JLBnumero10.setText("Numero do pedido:");

        JLBorigem10.setForeground(new java.awt.Color(255, 255, 255));
        JLBorigem10.setText("Endereço de origem:");

        JLBentragador10.setForeground(new java.awt.Color(255, 255, 255));
        JLBentragador10.setText("Entregador:");

        JLBdestino10.setForeground(new java.awt.Color(255, 255, 255));
        JLBdestino10.setText("Endereço de destino:");

        JLBdata10.setForeground(new java.awt.Color(255, 255, 255));
        JLBdata10.setText("Data de entrega:");

        JLBstatus10.setForeground(new java.awt.Color(255, 255, 255));
        JLBstatus10.setText("Status:");

        JTBexcluir10.setBackground(new java.awt.Color(255, 51, 51));
        JTBexcluir10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JTBexcluir10.setForeground(new java.awt.Color(255, 255, 255));
        JTBexcluir10.setText("EXCLUIR");
        JTBexcluir10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBexcluir10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPNfundo10Layout = new javax.swing.GroupLayout(JPNfundo10);
        JPNfundo10.setLayout(JPNfundo10Layout);
        JPNfundo10Layout.setHorizontalGroup(
            JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNfundo10Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNfundo10Layout.createSequentialGroup()
                        .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JPNfundo10Layout.createSequentialGroup()
                                .addComponent(JTBatualizar10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JTBexcluir10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTBvoltar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JPNtabelaencomenda10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(JPNfundo10Layout.createSequentialGroup()
                                .addComponent(JLBmotoconnect10, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JPNlista10, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JSPtabela10, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(173, 173, 173))
                    .addGroup(JPNfundo10Layout.createSequentialGroup()
                        .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFnumero10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBnumero10))
                        .addGap(44, 44, 44)
                        .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTForigem10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBorigem10))
                        .addGap(42, 42, 42)
                        .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLBentragador10)
                            .addComponent(JTFentragador10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFdestino10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBdestino10))
                        .addGap(36, 36, 36)
                        .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFdata10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBdata10))
                        .addGap(64, 64, 64)
                        .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFstatus10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBstatus10))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        JPNfundo10Layout.setVerticalGroup(
            JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNfundo10Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPNlista10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBmotoconnect10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(JPNtabelaencomenda10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JSPtabela10, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBnumero10)
                    .addComponent(JLBorigem10)
                    .addComponent(JLBentragador10)
                    .addComponent(JLBdestino10)
                    .addComponent(JLBdata10)
                    .addComponent(JLBstatus10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFnumero10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTForigem10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFentragador10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFdestino10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFdata10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFstatus10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTBatualizar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTBvoltar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTBexcluir10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNfundo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNfundo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTBvoltar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBvoltar10ActionPerformed
        // TODO add your handling code here:
        Tela_Lista_Encomendas.this.dispose();
        Tela_Menu JBTvoltar10 = new Tela_Menu();
        JBTvoltar10.setVisible(true);
    }//GEN-LAST:event_JTBvoltar10ActionPerformed

    private void JTBtabela10AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JTBtabela10AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_JTBtabela10AncestorAdded

    private void JTBatualizar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBatualizar10ActionPerformed
    String url = "jdbc:mysql://localhost:3306/mysql";
    String user = "root";
    String password = "";

    try {
        Connection conn = DriverManager.getConnection(url, user, password);

        // Para atualizar um registro
        String sqlUpdate = "UPDATE lista_encomendas SET nome_entregador = ?, endereco_destino = ? WHERE numero_pedido = ?";
        PreparedStatement statementUpdate = conn.prepareStatement(sqlUpdate);
        statementUpdate.setString(1, "novo_nome_entregador");
        statementUpdate.setString(2, "novo_endereco_destino");
        statementUpdate.setInt(3, 1);
        int rowsUpdated = statementUpdate.executeUpdate();
        if (rowsUpdated > 0) {
            System.out.println("A atualização foi feita com sucesso!");
        }

        // Para buscar um registro
        String sqlSelect = "SELECT * FROM lista_encomendas WHERE endereco_origem = ?";
        PreparedStatement statementSelect = conn.prepareStatement(sqlSelect);
        statementSelect.setString(1, "endereco_origem_especifico");
        ResultSet result = statementSelect.executeQuery();
        while (result.next()){
            String nome_entregador = result.getString("nome_entregador");
            String endereco_destino = result.getString("endereco_destino");
            System.out.println("Entregador: " + nome_entregador + ", Endereço de destino: " + endereco_destino);
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    
    }//GEN-LAST:event_JTBatualizar10ActionPerformed

    private void JTBexcluir10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBexcluir10ActionPerformed
    String url = "jdbc:mysql://localhost:3306/mysql";
    String user = "root";
    String password = "";

    try {
        Connection conn = DriverManager.getConnection(url, user, password);

        // Para excluir um registro
        String sqlDelete = "DELETE FROM lista_encomendas WHERE numero_pedido = ?";
        PreparedStatement statementDelete = conn.prepareStatement(sqlDelete);
        statementDelete.setInt(1, 1);
        int rowsDeleted = statementDelete.executeUpdate();
        if (rowsDeleted > 0) {
            System.out.println("A exclusão foi feita com sucesso!");
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_JTBexcluir10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Lista_Encomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Lista_Encomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Lista_Encomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Lista_Encomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Lista_Encomendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLBdata10;
    private javax.swing.JLabel JLBdestino10;
    private javax.swing.JLabel JLBentragador10;
    private javax.swing.JLabel JLBlista10;
    private javax.swing.JLabel JLBmotoconnect10;
    private javax.swing.JLabel JLBnumero10;
    private javax.swing.JLabel JLBorigem10;
    private javax.swing.JLabel JLBstatus10;
    private javax.swing.JLabel JLBtabelaencomenda10;
    private javax.swing.JPanel JPNfundo10;
    private javax.swing.JPanel JPNlista10;
    private javax.swing.JPanel JPNtabelaencomenda10;
    private javax.swing.JScrollPane JSPtabela10;
    private javax.swing.JButton JTBatualizar10;
    private javax.swing.JButton JTBexcluir10;
    private javax.swing.JTable JTBtabela10;
    private javax.swing.JButton JTBvoltar10;
    private javax.swing.JTextField JTFdata10;
    private javax.swing.JTextField JTFdestino10;
    private javax.swing.JTextField JTFentragador10;
    private javax.swing.JTextField JTFnumero10;
    private javax.swing.JTextField JTForigem10;
    private javax.swing.JTextField JTFstatus10;
    // End of variables declaration//GEN-END:variables
}
