/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motoconnect;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Tela_Informacoes_Destinatario extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Informacoes_Destinatario
     */
    public Tela_Informacoes_Destinatario() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPNfundo9 = new javax.swing.JPanel();
        JPNcadastrodecliente9 = new javax.swing.JPanel();
        JLBcadastrodecliente9 = new javax.swing.JLabel();
        JPNinformacoesdodestinatario9 = new javax.swing.JPanel();
        JLBinformacoesdodestinatario9 = new javax.swing.JLabel();
        JPNtiposdecargas9 = new javax.swing.JPanel();
        JLBtiposdecargas9 = new javax.swing.JLabel();
        JTFbairro9 = new javax.swing.JTextField();
        JTFcep9 = new javax.swing.JTextField();
        JTFdestinatario9 = new javax.swing.JTextField();
        JTFestado9 = new javax.swing.JTextField();
        JTFcidade9 = new javax.swing.JTextField();
        JTFrua9 = new javax.swing.JTextField();
        JTFnumero9 = new javax.swing.JTextField();
        JTFtelefone9 = new javax.swing.JTextField();
        JCBopcaoP19 = new javax.swing.JComboBox<>();
        JCBopcaoP29 = new javax.swing.JComboBox<>();
        JCBopcaoP39 = new javax.swing.JComboBox<>();
        JLBdestinatario9 = new javax.swing.JLabel();
        JLBcep9 = new javax.swing.JLabel();
        JLBbairro9 = new javax.swing.JLabel();
        JLBtelefone9 = new javax.swing.JLabel();
        JLBestado9 = new javax.swing.JLabel();
        JLBrua9 = new javax.swing.JLabel();
        JLBcidade9 = new javax.swing.JLabel();
        JLBnumero9 = new javax.swing.JLabel();
        JLBselecionar9 = new javax.swing.JLabel();
        JBTvoltar9 = new javax.swing.JButton();
        JBTcancelar9 = new javax.swing.JButton();
        JBTfinalizar9 = new javax.swing.JButton();
        JBTdetalhes9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPNfundo9.setBackground(new java.awt.Color(0, 51, 204));
        JPNfundo9.setPreferredSize(new java.awt.Dimension(1000, 600));

        JPNcadastrodecliente9.setBackground(new java.awt.Color(0, 102, 255));
        JPNcadastrodecliente9.setPreferredSize(new java.awt.Dimension(163, 50));

        JLBcadastrodecliente9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLBcadastrodecliente9.setForeground(new java.awt.Color(255, 255, 255));
        JLBcadastrodecliente9.setText("Cadastro do Cliente");

        javax.swing.GroupLayout JPNcadastrodecliente9Layout = new javax.swing.GroupLayout(JPNcadastrodecliente9);
        JPNcadastrodecliente9.setLayout(JPNcadastrodecliente9Layout);
        JPNcadastrodecliente9Layout.setHorizontalGroup(
            JPNcadastrodecliente9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNcadastrodecliente9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(JLBcadastrodecliente9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        JPNcadastrodecliente9Layout.setVerticalGroup(
            JPNcadastrodecliente9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNcadastrodecliente9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(JLBcadastrodecliente9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        JPNinformacoesdodestinatario9.setBackground(new java.awt.Color(0, 102, 255));
        JPNinformacoesdodestinatario9.setPreferredSize(new java.awt.Dimension(844, 30));

        JLBinformacoesdodestinatario9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLBinformacoesdodestinatario9.setForeground(new java.awt.Color(255, 255, 255));
        JLBinformacoesdodestinatario9.setText("Informações do Destinatario");

        javax.swing.GroupLayout JPNinformacoesdodestinatario9Layout = new javax.swing.GroupLayout(JPNinformacoesdodestinatario9);
        JPNinformacoesdodestinatario9.setLayout(JPNinformacoesdodestinatario9Layout);
        JPNinformacoesdodestinatario9Layout.setHorizontalGroup(
            JPNinformacoesdodestinatario9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNinformacoesdodestinatario9Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(JLBinformacoesdodestinatario9)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        JPNinformacoesdodestinatario9Layout.setVerticalGroup(
            JPNinformacoesdodestinatario9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNinformacoesdodestinatario9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBinformacoesdodestinatario9)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        JPNtiposdecargas9.setBackground(new java.awt.Color(0, 102, 255));
        JPNtiposdecargas9.setPreferredSize(new java.awt.Dimension(844, 30));

        JLBtiposdecargas9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLBtiposdecargas9.setForeground(new java.awt.Color(255, 255, 255));
        JLBtiposdecargas9.setText("Tipos de Carga");

        javax.swing.GroupLayout JPNtiposdecargas9Layout = new javax.swing.GroupLayout(JPNtiposdecargas9);
        JPNtiposdecargas9.setLayout(JPNtiposdecargas9Layout);
        JPNtiposdecargas9Layout.setHorizontalGroup(
            JPNtiposdecargas9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNtiposdecargas9Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(JLBtiposdecargas9)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        JPNtiposdecargas9Layout.setVerticalGroup(
            JPNtiposdecargas9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNtiposdecargas9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBtiposdecargas9)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        JTFbairro9.setBackground(new java.awt.Color(204, 204, 204));

        JTFcep9.setBackground(new java.awt.Color(204, 204, 204));
        JTFcep9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFcep9ActionPerformed(evt);
            }
        });

        JTFdestinatario9.setBackground(new java.awt.Color(204, 204, 204));
        JTFdestinatario9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFdestinatario9ActionPerformed(evt);
            }
        });

        JTFestado9.setBackground(new java.awt.Color(204, 204, 204));
        JTFestado9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFestado9ActionPerformed(evt);
            }
        });

        JTFcidade9.setBackground(new java.awt.Color(204, 204, 204));

        JTFrua9.setBackground(new java.awt.Color(204, 204, 204));
        JTFrua9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFrua9ActionPerformed(evt);
            }
        });

        JTFnumero9.setBackground(new java.awt.Color(204, 204, 204));

        JTFtelefone9.setBackground(new java.awt.Color(204, 204, 204));

        JCBopcaoP19.setBackground(new java.awt.Color(204, 204, 204));
        JCBopcaoP19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Documentos", "Encomendas Pequenas", "Pequenos Equipamentos", "Medicamentos e Suprimentos Médicos", "Produtos de Varejo" }));
        JCBopcaoP19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBopcaoP19ActionPerformed(evt);
            }
        });

        JCBopcaoP29.setBackground(new java.awt.Color(204, 204, 204));
        JCBopcaoP29.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Documentos", "Encomendas Pequenas", "Pequenos Equipamentos", "Medicamentos e Suprimentos Médicos", "Produtos de Varejo" }));
        JCBopcaoP29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBopcaoP29ActionPerformed(evt);
            }
        });

        JCBopcaoP39.setBackground(new java.awt.Color(204, 204, 204));
        JCBopcaoP39.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Documentos", "Encomendas Pequenas", "Pequenos Equipamentos", "Medicamentos e Suprimentos Médicos", "Produtos de Varejo" }));
        JCBopcaoP39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBopcaoP39ActionPerformed(evt);
            }
        });

        JLBdestinatario9.setForeground(new java.awt.Color(255, 255, 255));
        JLBdestinatario9.setText("Destinatario:");

        JLBcep9.setForeground(new java.awt.Color(255, 255, 255));
        JLBcep9.setText("CEP do destino:");

        JLBbairro9.setForeground(new java.awt.Color(255, 255, 255));
        JLBbairro9.setText("Bairro:");

        JLBtelefone9.setForeground(new java.awt.Color(255, 255, 255));
        JLBtelefone9.setText("Telefone do destinatario:");

        JLBestado9.setForeground(new java.awt.Color(255, 255, 255));
        JLBestado9.setText("Estado:");

        JLBrua9.setForeground(new java.awt.Color(255, 255, 255));
        JLBrua9.setText("Rua:");

        JLBcidade9.setForeground(new java.awt.Color(255, 255, 255));
        JLBcidade9.setText("Cidade:");

        JLBnumero9.setForeground(new java.awt.Color(255, 255, 255));
        JLBnumero9.setText("Numero:");

        JLBselecionar9.setForeground(new java.awt.Color(255, 255, 255));
        JLBselecionar9.setText("Selecione a abaixo:");

        JBTvoltar9.setBackground(new java.awt.Color(255, 51, 51));
        JBTvoltar9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JBTvoltar9.setForeground(new java.awt.Color(255, 255, 255));
        JBTvoltar9.setText("VOLTAR");
        JBTvoltar9.setMaximumSize(new java.awt.Dimension(106, 25));
        JBTvoltar9.setPreferredSize(new java.awt.Dimension(106, 25));
        JBTvoltar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTvoltar9ActionPerformed(evt);
            }
        });

        JBTcancelar9.setBackground(new java.awt.Color(255, 51, 51));
        JBTcancelar9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JBTcancelar9.setForeground(new java.awt.Color(255, 255, 255));
        JBTcancelar9.setText("CANCELAR");
        JBTcancelar9.setMaximumSize(new java.awt.Dimension(106, 25));
        JBTcancelar9.setPreferredSize(new java.awt.Dimension(106, 25));
        JBTcancelar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTcancelar9ActionPerformed(evt);
            }
        });

        JBTfinalizar9.setBackground(new java.awt.Color(255, 51, 51));
        JBTfinalizar9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JBTfinalizar9.setForeground(new java.awt.Color(255, 255, 255));
        JBTfinalizar9.setText("FINALIZAR");
        JBTfinalizar9.setMaximumSize(new java.awt.Dimension(106, 25));
        JBTfinalizar9.setPreferredSize(new java.awt.Dimension(106, 25));
        JBTfinalizar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTfinalizar9ActionPerformed(evt);
            }
        });

        JBTdetalhes9.setBackground(new java.awt.Color(255, 51, 51));
        JBTdetalhes9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JBTdetalhes9.setForeground(new java.awt.Color(255, 255, 255));
        JBTdetalhes9.setText("DETALHES DA ENCOMENDA");
        JBTdetalhes9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTdetalhes9ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\MotoConnect_Projeto\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\motoqueiro.png")); // NOI18N

        javax.swing.GroupLayout JPNfundo9Layout = new javax.swing.GroupLayout(JPNfundo9);
        JPNfundo9.setLayout(JPNfundo9Layout);
        JPNfundo9Layout.setHorizontalGroup(
            JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNfundo9Layout.createSequentialGroup()
                .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPNfundo9Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNfundo9Layout.createSequentialGroup()
                                .addComponent(JPNcadastrodecliente9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLBselecionar9)
                                    .addComponent(JPNtiposdecargas9, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNfundo9Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(JBTvoltar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(JBTdetalhes9)
                                .addGap(58, 58, 58)
                                .addComponent(JBTfinalizar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JPNfundo9Layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JPNinformacoesdodestinatario9, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPNfundo9Layout.createSequentialGroup()
                                .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLBcep9)
                                    .addComponent(JLBbairro9)
                                    .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(JTFbairro9, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JTFcep9, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPNfundo9Layout.createSequentialGroup()
                                        .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JLBrua9)
                                            .addComponent(JLBestado9))
                                        .addGap(200, 200, 200)
                                        .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JLBcidade9)
                                            .addComponent(JLBnumero9)))
                                    .addGroup(JPNfundo9Layout.createSequentialGroup()
                                        .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(JTFestado9, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                            .addComponent(JTFrua9))
                                        .addGap(18, 18, 18)
                                        .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JTFnumero9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JTFcidade9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(JPNfundo9Layout.createSequentialGroup()
                                .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNfundo9Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JTFdestinatario9, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNfundo9Layout.createSequentialGroup()
                                        .addComponent(JLBdestinatario9)
                                        .addGap(289, 289, 289)))
                                .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLBtelefone9)
                                    .addComponent(JTFtelefone9, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(JPNfundo9Layout.createSequentialGroup()
                                .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(JPNfundo9Layout.createSequentialGroup()
                                        .addComponent(JCBopcaoP19, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JCBopcaoP29, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JBTcancelar9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(JCBopcaoP39, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(42, 42, 42))
        );
        JPNfundo9Layout.setVerticalGroup(
            JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNfundo9Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(JPNinformacoesdodestinatario9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBdestinatario9)
                    .addComponent(JLBtelefone9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNfundo9Layout.createSequentialGroup()
                        .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFdestinatario9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFtelefone9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLBestado9)
                            .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JLBcidade9)
                                .addComponent(JLBcep9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFcep9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFestado9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFcidade9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLBbairro9)
                            .addComponent(JLBrua9)
                            .addComponent(JLBnumero9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFbairro9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFrua9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFnumero9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JPNtiposdecargas9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JPNcadastrodecliente9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(JLBselecionar9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCBopcaoP39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCBopcaoP29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCBopcaoP19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(JPNfundo9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBTvoltar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBTcancelar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBTdetalhes9)
                            .addComponent(JBTfinalizar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97))
                    .addGroup(JPNfundo9Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(JPNfundo9, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNfundo9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTvoltar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTvoltar9ActionPerformed
        // TODO add your handling code here:
        Tela_Informacoes_Destinatario.this.dispose();
        Tela_Cadastro_Cliente JBTvoltar9 = new Tela_Cadastro_Cliente();
        JBTvoltar9.setVisible(true);
    }//GEN-LAST:event_JBTvoltar9ActionPerformed

    private void JBTcancelar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTcancelar9ActionPerformed
        // TODO add your handling code here:
        Tela_Informacoes_Destinatario.this.dispose();
        Tela_Menu JBTcancelar9 = new Tela_Menu();
        JBTcancelar9.setVisible(true);
    }//GEN-LAST:event_JBTcancelar9ActionPerformed

    private void JBTfinalizar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTfinalizar9ActionPerformed
        try {    
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection com = DriverManager.getConnection("jdbc:mysql://localhost/moto_connect","root","");
            java.sql.Statement st = com.createStatement();
            
            st.executeUpdate ("INSERT INTO destinatario (destinatario, telefonedestinatario, cep, estado, cidade, bairro, rua, numero) VALUES("
                    +this.JTFdestinatario9.getText()+","
                    +this.JTFtelefone9.getText()+","
                    +this.JTFcep9.getText()+","
                    +this.JTFestado9.getText()+","
                    +this.JTFcidade9.getText()+","
                    +this.JTFbairro9.getText()+","
                    +this.JTFrua9.getText()+","                
                    +this.JTFnumero9.getText()+")");
            
            JOptionPane.showMessageDialog(null, "Informações enviadas");
            
                com.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao enviar informações: " + e.getMessage());
        }
        

        Tela_Informacoes_Destinatario.this.dispose();
        Tela_Menu JBTfinalizar9 = new Tela_Menu();
        JBTfinalizar9.setVisible(true);
    }//GEN-LAST:event_JBTfinalizar9ActionPerformed

    private void JCBopcaoP19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBopcaoP19ActionPerformed
        String opcao1 = (String) JCBopcaoP19.getSelectedItem();
        if (opcao1.equals("Selecione uma opção")) {
            JOptionPane.showMessageDialog(null, "Selecione uma opção válida!");
        } else {
            // Processa a opção selecionada
            System.out.println("Opção selecionada: " + opcao1);
        }
    }//GEN-LAST:event_JCBopcaoP19ActionPerformed

    private void JCBopcaoP29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBopcaoP29ActionPerformed
        String opcao2 = (String) JCBopcaoP29.getSelectedItem();
        if (opcao2.equals("Selecione uma opção")) {
            JOptionPane.showMessageDialog(null, "Selecione uma opção válida!");
        } else {
            // Processa a opção selecionada
            System.out.println("Opção selecionada: " + opcao2);
        }
    }//GEN-LAST:event_JCBopcaoP29ActionPerformed

    private void JCBopcaoP39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBopcaoP39ActionPerformed
        String opcao3 = (String) JCBopcaoP39.getSelectedItem();
        if (opcao3.equals("Selecione uma opção")) {
            JOptionPane.showMessageDialog(null, "Selecione uma opção válida!");
        } else {
            // Processa a opção selecionada
            System.out.println("Opção selecionada: " + opcao3);
        }
    }//GEN-LAST:event_JCBopcaoP39ActionPerformed

    private void JBTdetalhes9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTdetalhes9ActionPerformed
        // TODO add your handling code here:
        Tela_Informacoes_Destinatario.this.dispose();
        Tela_Detalhes_Encomenda JBTdetalhes9 = new Tela_Detalhes_Encomenda();
        JBTdetalhes9.setVisible(true);
    }//GEN-LAST:event_JBTdetalhes9ActionPerformed

    private void JTFdestinatario9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFdestinatario9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFdestinatario9ActionPerformed

    private void JTFcep9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFcep9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFcep9ActionPerformed

    private void JTFestado9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFestado9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFestado9ActionPerformed

    private void JTFrua9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFrua9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFrua9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Informacoes_Destinatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Informacoes_Destinatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Informacoes_Destinatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Informacoes_Destinatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Informacoes_Destinatario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTcancelar9;
    private javax.swing.JButton JBTdetalhes9;
    private javax.swing.JButton JBTfinalizar9;
    private javax.swing.JButton JBTvoltar9;
    private javax.swing.JComboBox<String> JCBopcaoP19;
    private javax.swing.JComboBox<String> JCBopcaoP29;
    private javax.swing.JComboBox<String> JCBopcaoP39;
    private javax.swing.JLabel JLBbairro9;
    private javax.swing.JLabel JLBcadastrodecliente9;
    private javax.swing.JLabel JLBcep9;
    private javax.swing.JLabel JLBcidade9;
    private javax.swing.JLabel JLBdestinatario9;
    private javax.swing.JLabel JLBestado9;
    private javax.swing.JLabel JLBinformacoesdodestinatario9;
    private javax.swing.JLabel JLBnumero9;
    private javax.swing.JLabel JLBrua9;
    private javax.swing.JLabel JLBselecionar9;
    private javax.swing.JLabel JLBtelefone9;
    private javax.swing.JLabel JLBtiposdecargas9;
    private javax.swing.JPanel JPNcadastrodecliente9;
    private javax.swing.JPanel JPNfundo9;
    private javax.swing.JPanel JPNinformacoesdodestinatario9;
    private javax.swing.JPanel JPNtiposdecargas9;
    private javax.swing.JTextField JTFbairro9;
    private javax.swing.JTextField JTFcep9;
    private javax.swing.JTextField JTFcidade9;
    private javax.swing.JTextField JTFdestinatario9;
    private javax.swing.JTextField JTFestado9;
    private javax.swing.JTextField JTFnumero9;
    private javax.swing.JTextField JTFrua9;
    private javax.swing.JTextField JTFtelefone9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
