/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motoconnect;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Tela_Calculo_Frete extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Calculo_Frete
     */
    public Tela_Calculo_Frete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JBTvoltar7 = new javax.swing.JButton();
        JBTcadastrodocliente7 = new javax.swing.JButton();
        JTFcidadededestino7 = new javax.swing.JTextField();
        JTFpesodamercadoria7 = new javax.swing.JTextField();
        JTFcidadedeorigem7 = new javax.swing.JTextField();
        JLBpesodamercadoria7 = new javax.swing.JLabel();
        JLBcidadedeorigem7 = new javax.swing.JLabel();
        JLBcidadededestino7 = new javax.swing.JLabel();
        JPNregistrocalculodefrete7 = new javax.swing.JPanel();
        JLBregistrocalculodefrete7 = new javax.swing.JLabel();
        JLBopcoesdeentregas7 = new javax.swing.JLabel();
        RBTentregaprograma7 = new javax.swing.JRadioButton();
        RBTexpress7 = new javax.swing.JRadioButton();
        JLBvalordofrete7 = new javax.swing.JLabel();
        JTFvalor7 = new javax.swing.JTextField();
        JBTcalcular7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));

        JBTvoltar7.setBackground(new java.awt.Color(255, 51, 51));
        JBTvoltar7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JBTvoltar7.setForeground(new java.awt.Color(255, 255, 255));
        JBTvoltar7.setText("VOLTAR");
        JBTvoltar7.setMaximumSize(new java.awt.Dimension(106, 25));
        JBTvoltar7.setPreferredSize(new java.awt.Dimension(106, 25));
        JBTvoltar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTvoltar7ActionPerformed(evt);
            }
        });

        JBTcadastrodocliente7.setBackground(new java.awt.Color(255, 51, 51));
        JBTcadastrodocliente7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JBTcadastrodocliente7.setForeground(new java.awt.Color(255, 255, 255));
        JBTcadastrodocliente7.setText("CADASTRO DO CLIENTE");
        JBTcadastrodocliente7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTcadastrodocliente7ActionPerformed(evt);
            }
        });

        JTFcidadededestino7.setBackground(new java.awt.Color(204, 204, 204));
        JTFcidadededestino7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFcidadededestino7ActionPerformed(evt);
            }
        });

        JTFpesodamercadoria7.setBackground(new java.awt.Color(204, 204, 204));
        JTFpesodamercadoria7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFpesodamercadoria7ActionPerformed(evt);
            }
        });

        JTFcidadedeorigem7.setBackground(new java.awt.Color(204, 204, 204));
        JTFcidadedeorigem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFcidadedeorigem7ActionPerformed(evt);
            }
        });

        JLBpesodamercadoria7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLBpesodamercadoria7.setForeground(new java.awt.Color(255, 255, 255));
        JLBpesodamercadoria7.setText("Peso da Mercadoria:");

        JLBcidadedeorigem7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLBcidadedeorigem7.setForeground(new java.awt.Color(255, 255, 255));
        JLBcidadedeorigem7.setText("Cidade de origem:");

        JLBcidadededestino7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLBcidadededestino7.setForeground(new java.awt.Color(255, 255, 255));
        JLBcidadededestino7.setText("Cidade de destino:");

        JPNregistrocalculodefrete7.setBackground(new java.awt.Color(0, 102, 255));
        JPNregistrocalculodefrete7.setPreferredSize(new java.awt.Dimension(844, 30));

        JLBregistrocalculodefrete7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLBregistrocalculodefrete7.setForeground(new java.awt.Color(255, 255, 255));
        JLBregistrocalculodefrete7.setText("Registro de calculo de frete");

        javax.swing.GroupLayout JPNregistrocalculodefrete7Layout = new javax.swing.GroupLayout(JPNregistrocalculodefrete7);
        JPNregistrocalculodefrete7.setLayout(JPNregistrocalculodefrete7Layout);
        JPNregistrocalculodefrete7Layout.setHorizontalGroup(
            JPNregistrocalculodefrete7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNregistrocalculodefrete7Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(JLBregistrocalculodefrete7)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        JPNregistrocalculodefrete7Layout.setVerticalGroup(
            JPNregistrocalculodefrete7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNregistrocalculodefrete7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBregistrocalculodefrete7)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        JLBopcoesdeentregas7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLBopcoesdeentregas7.setForeground(new java.awt.Color(255, 255, 255));
        JLBopcoesdeentregas7.setText("Opções de entraga:");

        RBTentregaprograma7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        RBTentregaprograma7.setForeground(new java.awt.Color(255, 255, 255));
        RBTentregaprograma7.setText("Entrega programada");
        RBTentregaprograma7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTentregaprograma7ActionPerformed(evt);
            }
        });

        RBTexpress7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        RBTexpress7.setForeground(new java.awt.Color(255, 255, 255));
        RBTexpress7.setText("Express");
        RBTexpress7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTexpress7ActionPerformed(evt);
            }
        });

        JLBvalordofrete7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLBvalordofrete7.setForeground(new java.awt.Color(255, 255, 255));
        JLBvalordofrete7.setText("Valor do Frete:");

        JTFvalor7.setBackground(new java.awt.Color(204, 204, 204));
        JTFvalor7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFvalor7ActionPerformed(evt);
            }
        });

        JBTcalcular7.setBackground(new java.awt.Color(255, 51, 51));
        JBTcalcular7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JBTcalcular7.setForeground(new java.awt.Color(255, 255, 255));
        JBTcalcular7.setText("CALCULAR");
        JBTcalcular7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTcalcular7ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 51, 51));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Menos de 1kg", "R$ 3,00"},
                {"De 1kg ate 2,9kg", "R$ 5,00"},
                {"De 3kg ate 7,9kg", "R$ 9,00"},
                {"De 8kg ate 12kg", "R$ 12,00"},
                {"Acima 12kg", "Não e possivel transportar"},
                {null, null}
            },
            new String [] {
                "Peso da Mercadoria", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setBackground(new java.awt.Color(255, 51, 51));
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1 munito de deslocamento", "R$ 0,30"},
                {".", "."}
            },
            new String [] {
                "1 minuto de deslocamento", "Preço"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setBackground(new java.awt.Color(255, 51, 51));
        jTable3.setForeground(new java.awt.Color(255, 255, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1 km rodado", "R$ 0,50"},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "1 km rodado", "Preço"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JBTvoltar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JBTcadastrodocliente7)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JLBpesodamercadoria7)
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(JTFcidadededestino7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                                    .addComponent(JTFcidadedeorigem7)
                                                    .addComponent(JTFpesodamercadoria7)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(JTFvalor7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(JBTcalcular7))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(RBTentregaprograma7)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(RBTexpress7))))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(168, 168, 168)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JLBcidadedeorigem7)
                                            .addComponent(JLBcidadededestino7)
                                            .addComponent(JLBvalordofrete7)
                                            .addComponent(JLBopcoesdeentregas7))
                                        .addGap(269, 269, 269)))))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JPNregistrocalculodefrete7, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(JPNregistrocalculodefrete7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFpesodamercadoria7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBpesodamercadoria7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFcidadedeorigem7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBcidadedeorigem7))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFcidadededestino7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBcidadededestino7))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLBopcoesdeentregas7)
                            .addComponent(RBTentregaprograma7)
                            .addComponent(RBTexpress7)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBvalordofrete7)
                    .addComponent(JTFvalor7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTcalcular7))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBTvoltar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBTcadastrodocliente7))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTcalcular7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTcalcular7ActionPerformed
    // TODO add your handling code here:
    String cidadeOrigem = JTFcidadedeorigem7.getText();
    String cidadeDestino = JTFcidadededestino7.getText();
    double pesoMercadoria = Double.parseDouble(JTFpesodamercadoria7.getText());

    // Define as distâncias e os tempos de deslocamento entre as cidades da Grande Vitória
    double[][] distancias = {
           
            /* Vitória */   {0, 15.1, 35.8, 15.1, 9.5},
            /* Vila Velha */{15.1, 0, 38.2, 20, 20},
            /* Serra */     {35.8, 38.2, 0, 30, 44},
            /* Cariacica */ {15.1, 20, 30, 0, 20},
            /* Viana */     {9.5, 20, 44, 20, 0}
    };

    double[][] tempos = {
            
            /* Vitória */   {0, 31, 44, 31, 15},
            /* Vila Velha */{31, 0, 45, 40, 45},
            /* Serra */     {44, 45, 0, 60, 90},
            /* Cariacica */ {31, 40, 60, 0, 80},
            /* Viana */     {15, 45, 90, 80, 0}
    };

    // Índices das cidades no array
    String[] cidades = {"Vitória", "Vila Velha", "Serra", "Cariacica", "Viana"};

    int indiceOrigem = -1;
    int indiceDestino = -1;

    // Encontra os índices das cidades no array
    for (int i = 0; i < cidades.length; i++) {
        if (cidades[i].equalsIgnoreCase(cidadeOrigem)) {
            indiceOrigem = i;
        }
        if (cidades[i].equalsIgnoreCase(cidadeDestino)) {
            indiceDestino = i;
        }
    }

    // Verifica se as cidades são válidas
    if (indiceOrigem == -1 || indiceDestino == -1) {
        JOptionPane.showMessageDialog(this, "Cidades inválidas. Por favor, insira cidades da Grande Vitória.");
        return;
    }

    // Obtém a distância e o tempo de deslocamento entre as cidades
    double distanciaKm = distancias[indiceOrigem][indiceDestino];
    double tempoDeslocamentoMinutos = tempos[indiceOrigem][indiceDestino];

    // Calcula o custo com base no peso da mercadoria
    double valorPeso;
    if (pesoMercadoria < 1) {
        valorPeso = 3.00;
    } else if (pesoMercadoria >= 1 && pesoMercadoria <= 2.9) {
        valorPeso = 5.00;
    } else if (pesoMercadoria >= 3 && pesoMercadoria <= 7.9) {
        valorPeso = 9.00;
    } else if (pesoMercadoria >= 8 && pesoMercadoria <= 12) {
        valorPeso = 12.00;
    } else {
        JOptionPane.showMessageDialog(this, "Não é possível transportar mercadorias acima de 12 Kg.");
        return;
    }

    // Calcula os custos adicionais
    double custoPorKm = 0.50;
    double custoPorMinuto = 0.30;
    double valorDistancia = distanciaKm * custoPorKm;
    double valorTempo = tempoDeslocamentoMinutos * custoPorMinuto;

    // Calcula o valor total do frete
    double valorTotalFrete = valorPeso + valorDistancia + valorTempo;

    // Verifica se o usuário escolheu entrega expressa e calcula o valor final do frete
    if (RBTexpress7.isSelected()) {
        valorTotalFrete *= 1.15; // Aumenta o valor total em 15%
    }

    // Exibe o resultado
    JTFvalor7.setText(String.format("R$ %.2f", valorTotalFrete));
   
    }//GEN-LAST:event_JBTcalcular7ActionPerformed

    private void JTFvalor7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFvalor7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFvalor7ActionPerformed

    private void JTFpesodamercadoria7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFpesodamercadoria7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFpesodamercadoria7ActionPerformed

    private void JTFcidadedeorigem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFcidadedeorigem7ActionPerformed
        // TODO add your handling code here:
        // Ação a ser realizada quando o campo de cidade de origem for utilizado
        // Exemplo: Validar a cidade de origem ou atualizar a interface
        System.out.println("Cidade de origem inserida: " + JTFcidadedeorigem7.getText());
    }//GEN-LAST:event_JTFcidadedeorigem7ActionPerformed

    private void JTFcidadededestino7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFcidadededestino7ActionPerformed
        // TODO add your handling code here:
        // Ação a ser realizada quando o campo de cidade de destino for utilizado
        // Exemplo: Validar a cidade de destino ou atualizar a interface
        System.out.println("Cidade de destino inserida: " + JTFcidadededestino7.getText());

    }//GEN-LAST:event_JTFcidadededestino7ActionPerformed

    private void RBTentregaprograma7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTentregaprograma7ActionPerformed
        // Ação a ser realizada quando o campo de cidade de destino for utilizado
        // Exemplo: Validar a cidade de destino ou atualizar a interface
        if (RBTentregaprograma7.isSelected()) {
        System.out.println("Entrega programada selecionada.");
        }
    }//GEN-LAST:event_RBTentregaprograma7ActionPerformed

    private void RBTexpress7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTexpress7ActionPerformed
        // Ação a ser realizada quando a opção de entrega expressa for selecionada
        // Exemplo: Atualizar uma variável de estado ou a interface
        if (RBTexpress7.isSelected()) {
        System.out.println("Entrega express selecionada.");
        }
    }//GEN-LAST:event_RBTexpress7ActionPerformed

    private void JBTvoltar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTvoltar7ActionPerformed
        // TODO add your handling code here:
        Tela_Calculo_Frete.this.dispose();
        Tela_Tipo_Carga JBTvoltar7 = new Tela_Tipo_Carga();
        JBTvoltar7.setVisible(true);
    }//GEN-LAST:event_JBTvoltar7ActionPerformed

    private void JBTcadastrodocliente7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTcadastrodocliente7ActionPerformed
        // TODO add your handling code here:
        Tela_Calculo_Frete.this.dispose();
        Tela_Cadastro_Cliente JBTcadastrodocliente7 = new Tela_Cadastro_Cliente();
        JBTcadastrodocliente7.setVisible(true);
    }//GEN-LAST:event_JBTcadastrodocliente7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Calculo_Frete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Calculo_Frete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Calculo_Frete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Calculo_Frete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Calculo_Frete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTcadastrodocliente7;
    private javax.swing.JButton JBTcalcular7;
    private javax.swing.JButton JBTvoltar7;
    private javax.swing.JLabel JLBcidadededestino7;
    private javax.swing.JLabel JLBcidadedeorigem7;
    private javax.swing.JLabel JLBopcoesdeentregas7;
    private javax.swing.JLabel JLBpesodamercadoria7;
    private javax.swing.JLabel JLBregistrocalculodefrete7;
    private javax.swing.JLabel JLBvalordofrete7;
    private javax.swing.JPanel JPNregistrocalculodefrete7;
    private javax.swing.JTextField JTFcidadededestino7;
    private javax.swing.JTextField JTFcidadedeorigem7;
    private javax.swing.JTextField JTFpesodamercadoria7;
    private javax.swing.JTextField JTFvalor7;
    private javax.swing.JRadioButton RBTentregaprograma7;
    private javax.swing.JRadioButton RBTexpress7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
