/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motoconnect;

/**
 *
 * @author PC
 */
public class Tela_Cadastro_Funcionario extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Cadastro_Funcionario
     */
    public Tela_Cadastro_Funcionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPNfundo3 = new javax.swing.JPanel();
        JPNazulclaro3 = new javax.swing.JPanel();
        JBTentregador3 = new javax.swing.JButton();
        JBTatendente3 = new javax.swing.JButton();
        JLBcadastrodefuncionario3 = new javax.swing.JLabel();
        JLBou3 = new javax.swing.JLabel();
        JLBmotoconnect3 = new javax.swing.JLabel();
        JBTvoltar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPNfundo3.setBackground(new java.awt.Color(0, 51, 204));
        JPNfundo3.setPreferredSize(new java.awt.Dimension(1000, 600));

        JPNazulclaro3.setBackground(new java.awt.Color(0, 102, 255));
        JPNazulclaro3.setPreferredSize(new java.awt.Dimension(402, 491));

        JBTentregador3.setBackground(new java.awt.Color(0, 51, 204));
        JBTentregador3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JBTentregador3.setForeground(new java.awt.Color(255, 255, 255));
        JBTentregador3.setText("Entregador");
        JBTentregador3.setMaximumSize(new java.awt.Dimension(115, 25));
        JBTentregador3.setPreferredSize(new java.awt.Dimension(115, 25));
        JBTentregador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTentregador3ActionPerformed(evt);
            }
        });

        JBTatendente3.setBackground(new java.awt.Color(0, 51, 204));
        JBTatendente3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JBTatendente3.setForeground(new java.awt.Color(255, 255, 255));
        JBTatendente3.setText("Atendente");
        JBTatendente3.setMaximumSize(new java.awt.Dimension(115, 25));
        JBTatendente3.setPreferredSize(new java.awt.Dimension(115, 25));
        JBTatendente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTatendente3ActionPerformed(evt);
            }
        });

        JLBcadastrodefuncionario3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLBcadastrodefuncionario3.setForeground(new java.awt.Color(255, 255, 255));
        JLBcadastrodefuncionario3.setText("Cadastro de funcionario:");

        JLBou3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLBou3.setForeground(new java.awt.Color(255, 255, 255));
        JLBou3.setText("ou");

        JLBmotoconnect3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\MotoConnect_Projeto\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\motoqueiro.png")); // NOI18N

        javax.swing.GroupLayout JPNazulclaro3Layout = new javax.swing.GroupLayout(JPNazulclaro3);
        JPNazulclaro3.setLayout(JPNazulclaro3Layout);
        JPNazulclaro3Layout.setHorizontalGroup(
            JPNazulclaro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNazulclaro3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPNazulclaro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNazulclaro3Layout.createSequentialGroup()
                        .addGroup(JPNazulclaro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBTatendente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBTentregador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNazulclaro3Layout.createSequentialGroup()
                        .addComponent(JLBou3)
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNazulclaro3Layout.createSequentialGroup()
                        .addComponent(JLBcadastrodefuncionario3)
                        .addGap(126, 126, 126))))
            .addGroup(JPNazulclaro3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(JLBmotoconnect3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 94, Short.MAX_VALUE))
        );
        JPNazulclaro3Layout.setVerticalGroup(
            JPNazulclaro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNazulclaro3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(JLBmotoconnect3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(JLBcadastrodefuncionario3)
                .addGap(18, 18, 18)
                .addComponent(JBTatendente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLBou3)
                .addGap(19, 19, 19)
                .addComponent(JBTentregador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        JBTvoltar3.setBackground(new java.awt.Color(255, 51, 51));
        JBTvoltar3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        JBTvoltar3.setForeground(new java.awt.Color(255, 255, 255));
        JBTvoltar3.setText("VOLTAR");
        JBTvoltar3.setMaximumSize(new java.awt.Dimension(75, 30));
        JBTvoltar3.setPreferredSize(new java.awt.Dimension(70, 30));
        JBTvoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTvoltar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPNfundo3Layout = new javax.swing.GroupLayout(JPNfundo3);
        JPNfundo3.setLayout(JPNfundo3Layout);
        JPNfundo3Layout.setHorizontalGroup(
            JPNfundo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNfundo3Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(JBTvoltar3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(JPNazulclaro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        JPNfundo3Layout.setVerticalGroup(
            JPNfundo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNfundo3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(JPNfundo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNfundo3Layout.createSequentialGroup()
                        .addComponent(JPNazulclaro3, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNfundo3Layout.createSequentialGroup()
                        .addComponent(JBTvoltar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNfundo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPNfundo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTvoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTvoltar3ActionPerformed
        // Fecha a janela atual (Tela_Cadastro_Funcionario) e abre a tela do menu (Tela_Menu)
        Tela_Cadastro_Funcionario.this.dispose();
        Tela_Menu JBTvoltar3 = new Tela_Menu();
        JBTvoltar3.setVisible(true);
    }//GEN-LAST:event_JBTvoltar3ActionPerformed

    private void JBTatendente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTatendente3ActionPerformed
        // Fecha a janela atual (Tela_Cadastro_Funcionario) e abre a tela de informações do atendente (Tela_Informacoes_Atendente)
        Tela_Cadastro_Funcionario.this.dispose();
        Tela_Informacoes_Atendente JBTatendente3 = new Tela_Informacoes_Atendente();
        JBTatendente3.setVisible(true);
    }//GEN-LAST:event_JBTatendente3ActionPerformed

    private void JBTentregador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTentregador3ActionPerformed
        // Fecha a janela atual (Tela_Cadastro_Funcionario) e abre a tela de informações do entregador (Tela_Informacoes_Entregador)
        Tela_Cadastro_Funcionario.this.dispose();
        Tela_Informacoes_Entregador JBTentregador3 = new Tela_Informacoes_Entregador();
        JBTentregador3.setVisible(true);
    }//GEN-LAST:event_JBTentregador3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cadastro_Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTatendente3;
    private javax.swing.JButton JBTentregador3;
    private javax.swing.JButton JBTvoltar3;
    private javax.swing.JLabel JLBcadastrodefuncionario3;
    private javax.swing.JLabel JLBmotoconnect3;
    private javax.swing.JLabel JLBou3;
    private javax.swing.JPanel JPNazulclaro3;
    private javax.swing.JPanel JPNfundo3;
    // End of variables declaration//GEN-END:variables
}
