/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motoconnect;

/**
 *
 * @author PC
 */
public class Tela_Menu extends javax.swing.JFrame {

    /**
     * Creates new form MotoConnect_Menu
     */
    public Tela_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPNazulescuro2 = new javax.swing.JPanel();
        JBTcadastrodefubcionario2 = new javax.swing.JButton();
        JBTregistrocalculodefrete2 = new javax.swing.JButton();
        JBTobservacoesecomentarios2 = new javax.swing.JButton();
        JBTalertas2 = new javax.swing.JButton();
        JBTcadastrodecliente2 = new javax.swing.JButton();
        JPNusuario2 = new javax.swing.JPanel();
        JLBbemvindo2 = new javax.swing.JLabel();
        JTFusuario2 = new javax.swing.JTextField();
        JLBmotoconnect2 = new javax.swing.JLabel();
        JTBlistaencomendas2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JLBparavermelha2 = new javax.swing.JPanel();
        JLBcadastrodefuncionario2 = new javax.swing.JLabel();
        JLBregistrodecalculofrete2 = new javax.swing.JLabel();
        JLBcadastrodecliente2 = new javax.swing.JLabel();
        JLBobservacoesecomentarios2 = new javax.swing.JLabel();
        JLBlistaencomenda2 = new javax.swing.JLabel();
        JLBalertas2 = new javax.swing.JLabel();
        JLBsair2 = new javax.swing.JLabel();
        JBTsair2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPNazulescuro2.setBackground(new java.awt.Color(0, 51, 204));
        JPNazulescuro2.setPreferredSize(new java.awt.Dimension(1000, 600));
        JPNazulescuro2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBTcadastrodefubcionario2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\MotoConnect_Projeto\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\Cadastro de Funcionario.png")); // NOI18N
        JBTcadastrodefubcionario2.setContentAreaFilled(false);
        JBTcadastrodefubcionario2.setMaximumSize(new java.awt.Dimension(50, 50));
        JBTcadastrodefubcionario2.setMinimumSize(new java.awt.Dimension(0, 0));
        JBTcadastrodefubcionario2.setPreferredSize(new java.awt.Dimension(50, 50));
        JBTcadastrodefubcionario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTcadastrodefubcionario2ActionPerformed(evt);
            }
        });
        JPNazulescuro2.add(JBTcadastrodefubcionario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 50, 50));

        JBTregistrocalculodefrete2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\MotoConnect_Projeto\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\Calculo de frete.png")); // NOI18N
        JBTregistrocalculodefrete2.setContentAreaFilled(false);
        JBTregistrocalculodefrete2.setMaximumSize(new java.awt.Dimension(50, 50));
        JBTregistrocalculodefrete2.setMinimumSize(new java.awt.Dimension(50, 50));
        JBTregistrocalculodefrete2.setPreferredSize(new java.awt.Dimension(50, 50));
        JBTregistrocalculodefrete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTregistrocalculodefrete2ActionPerformed(evt);
            }
        });
        JPNazulescuro2.add(JBTregistrocalculodefrete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 50, 50));

        JBTobservacoesecomentarios2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\MotoConnect_Projeto\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\Observações e Comentarios.png")); // NOI18N
        JBTobservacoesecomentarios2.setContentAreaFilled(false);
        JBTobservacoesecomentarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTobservacoesecomentarios2ActionPerformed(evt);
            }
        });
        JPNazulescuro2.add(JBTobservacoesecomentarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 50, 50));

        JBTalertas2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\MotoConnect_Projeto\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\Alertas.png")); // NOI18N
        JBTalertas2.setContentAreaFilled(false);
        JPNazulescuro2.add(JBTalertas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 50, 50));

        JBTcadastrodecliente2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\MotoConnect_Projeto\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\Cadastro de Cliente.png")); // NOI18N
        JBTcadastrodecliente2.setContentAreaFilled(false);
        JBTcadastrodecliente2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBTcadastrodecliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTcadastrodecliente2ActionPerformed(evt);
            }
        });
        JPNazulescuro2.add(JBTcadastrodecliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 50, 50));

        JPNusuario2.setBackground(new java.awt.Color(0, 102, 255));

        JLBbemvindo2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLBbemvindo2.setForeground(new java.awt.Color(255, 255, 255));
        JLBbemvindo2.setText("Bem vindo !");

        JTFusuario2.setBackground(new java.awt.Color(0, 102, 255));
        JTFusuario2.setForeground(new java.awt.Color(255, 255, 255));
        JTFusuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFusuario2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPNusuario2Layout = new javax.swing.GroupLayout(JPNusuario2);
        JPNusuario2.setLayout(JPNusuario2Layout);
        JPNusuario2Layout.setHorizontalGroup(
            JPNusuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNusuario2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JLBbemvindo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFusuario2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPNusuario2Layout.setVerticalGroup(
            JPNusuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNusuario2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(JPNusuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBbemvindo2)
                    .addComponent(JTFusuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        JPNazulescuro2.add(JPNusuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 300, 60));
        JPNazulescuro2.add(JLBmotoconnect2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 110));

        JTBlistaencomendas2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\MotoConnect_Projeto\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\5-removebg-preview (1).png")); // NOI18N
        JTBlistaencomendas2.setContentAreaFilled(false);
        JTBlistaencomendas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBlistaencomendas2ActionPerformed(evt);
            }
        });
        JPNazulescuro2.add(JTBlistaencomendas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\MotoConnect_Projeto\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\motoqueiro.png")); // NOI18N
        JPNazulescuro2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 240, 120));

        JLBparavermelha2.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout JLBparavermelha2Layout = new javax.swing.GroupLayout(JLBparavermelha2);
        JLBparavermelha2.setLayout(JLBparavermelha2Layout);
        JLBparavermelha2Layout.setHorizontalGroup(
            JLBparavermelha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        JLBparavermelha2Layout.setVerticalGroup(
            JLBparavermelha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        JPNazulescuro2.add(JLBparavermelha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1000, 20));
        JPNazulescuro2.add(JLBcadastrodefuncionario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));
        JPNazulescuro2.add(JLBregistrodecalculofrete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));
        JPNazulescuro2.add(JLBcadastrodecliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));
        JPNazulescuro2.add(JLBobservacoesecomentarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 50, 60));
        JPNazulescuro2.add(JLBlistaencomenda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));
        JPNazulescuro2.add(JLBalertas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        JLBsair2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\MotoConnect_Projeto\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\Sair.png")); // NOI18N
        JPNazulescuro2.add(JLBsair2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, 50, 60));

        JBTsair2.setContentAreaFilled(false);
        JBTsair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTsair2ActionPerformed(evt);
            }
        });
        JPNazulescuro2.add(JBTsair2, new org.netbeans.lib.awtextra.AbsoluteConstraints(892, 490, 50, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNazulescuro2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNazulescuro2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTcadastrodefubcionario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTcadastrodefubcionario2ActionPerformed
        // TODO add your handling code here:
        Tela_Menu.this.dispose();
        Tela_Cadastro_Funcionario JBTcadastrodefuncionario2 = new Tela_Cadastro_Funcionario();
        JBTcadastrodefuncionario2.setVisible(true);
    }//GEN-LAST:event_JBTcadastrodefubcionario2ActionPerformed

    private void JBTregistrocalculodefrete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTregistrocalculodefrete2ActionPerformed
        // TODO add your handling code here:
        Tela_Menu.this.dispose();
        Tela_Tipo_Carga JBTregistrocalculodefrete2 = new Tela_Tipo_Carga();
        JBTregistrocalculodefrete2.setVisible(true);
    }//GEN-LAST:event_JBTregistrocalculodefrete2ActionPerformed

    private void JBTcadastrodecliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTcadastrodecliente2ActionPerformed
        // TODO add your handling code here:
        Tela_Menu.this.dispose();
        Tela_Cadastro_Cliente JBTcadastrodecliente2 = new Tela_Cadastro_Cliente();
        JBTcadastrodecliente2.setVisible(true);
    }//GEN-LAST:event_JBTcadastrodecliente2ActionPerformed

    private void JBTobservacoesecomentarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTobservacoesecomentarios2ActionPerformed
        // TODO add your handling code here:
        Tela_Menu.this.dispose();
        Tela_Observacoes_Comentarioes JBTobservacoesecomentarios2 = new Tela_Observacoes_Comentarioes();
        JBTobservacoesecomentarios2.setVisible(true);
    }//GEN-LAST:event_JBTobservacoesecomentarios2ActionPerformed

    private void JTBlistaencomendas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBlistaencomendas2ActionPerformed
        // TODO add your handling code here:
        Tela_Menu.this.dispose();
        Tela_Lista_Encomendas JTBlistaencomendas2 = new Tela_Lista_Encomendas();
        JTBlistaencomendas2.setVisible(true);
    }//GEN-LAST:event_JTBlistaencomendas2ActionPerformed

    private void JBTsair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTsair2ActionPerformed
        // TODO add your handling code here:
        Tela_Menu.this.dispose();
        Tela_Login JBTsair2 = new Tela_Login();
        JBTsair2.setVisible(true);
    }//GEN-LAST:event_JBTsair2ActionPerformed

    private void JTFusuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFusuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFusuario2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTalertas2;
    private javax.swing.JButton JBTcadastrodecliente2;
    private javax.swing.JButton JBTcadastrodefubcionario2;
    private javax.swing.JButton JBTobservacoesecomentarios2;
    private javax.swing.JButton JBTregistrocalculodefrete2;
    private javax.swing.JButton JBTsair2;
    private javax.swing.JLabel JLBalertas2;
    private javax.swing.JLabel JLBbemvindo2;
    private javax.swing.JLabel JLBcadastrodecliente2;
    private javax.swing.JLabel JLBcadastrodefuncionario2;
    private javax.swing.JLabel JLBlistaencomenda2;
    private javax.swing.JLabel JLBmotoconnect2;
    private javax.swing.JLabel JLBobservacoesecomentarios2;
    private javax.swing.JPanel JLBparavermelha2;
    private javax.swing.JLabel JLBregistrodecalculofrete2;
    private javax.swing.JLabel JLBsair2;
    private javax.swing.JPanel JPNazulescuro2;
    private javax.swing.JPanel JPNusuario2;
    private javax.swing.JButton JTBlistaencomendas2;
    private javax.swing.JTextField JTFusuario2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
