/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motoconnect;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Tela_Lista_Encomendas extends javax.swing.JFrame {
    
    private static final String URI = "jdbc:mysql://localhost:3306/crud";
    private static final String USUARIO = "root";
    private static final String SENHA = "";

    private Connection conexao;
    private DefaultTableModel model;

    /**
     * Creates new form Tela_Lista_Encomendas
     */
    public Tela_Lista_Encomendas() {
        initComponents();
        model = (DefaultTableModel) JTBtabela10.getModel();
        conectarBanco();
        atualizarTabela();
        
    }
    
    private void conectarBanco() {
        try {
            conexao = DriverManager.getConnection(URI, USUARIO, SENHA);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao conectar ao banco de dados: " + ex.getMessage());
        }
    }

    private void atualizarTabela() {
        model.setRowCount(0); // Limpa todas as linhas da tabela antes de recarregar

        String sql = "SELECT e.numero_pedido, cf.cidade_origem, ent.nome AS nome_entregador, cf.cidade_destino, e.data_entrega, e.statuss "
                   + "FROM encomendas e "
                   + "JOIN calculo_frete cf ON e.numero_pedido = cf.numero_pedido "
                   + "JOIN entregador ent ON e.id_entregador = ent.id_entregador";

        try (PreparedStatement statement = conexao.prepareStatement(sql);
             ResultSet rs = statement.executeQuery()) {

            while (rs.next()) {
                int numeroPedido = rs.getInt("numero_pedido");
                String cidadeOrigem = rs.getString("cidade_origem");
                String nomeEntregador = rs.getString("nome_entregador");
                String cidadeDestino = rs.getString("cidade_destino");
                Date dataEntrega = rs.getDate("data_entrega");
                String status = rs.getString("statuss");

                // Montar linha para adicionar ao modelo da tabela
                Object[] row = {
                    numeroPedido,
                    cidadeOrigem,
                    nomeEntregador,
                    cidadeDestino,
                    dataEntrega,
                    status
                };
                model.addRow(row); // Adiciona a linha ao modelo da tabela
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados da tabela: " + ex.getMessage());
        }
    }

    private void excluirPedido() {
        String numeroPedidoStr = JTFnumero10.getText().trim();
        if (!numeroPedidoStr.isEmpty()) {
            try {
                int numeroPedido = Integer.parseInt(numeroPedidoStr);
                String sqlDelete = "DELETE FROM encomendas WHERE numero_pedido = ?";
                try (PreparedStatement statement = conexao.prepareStatement(sqlDelete)) {
                    statement.setInt(1, numeroPedido);

                    int rowsDeleted = statement.executeUpdate();

                    if (rowsDeleted > 0) {
                        JOptionPane.showMessageDialog(null, "Pedido excluído com sucesso!");
                        atualizarTabela();
                    } else {
                        JOptionPane.showMessageDialog(null, "Falha ao excluir pedido.");
                    }
                }
            } catch (NumberFormatException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao excluir pedido: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Digite um número de pedido para excluir.");
        }
    }

    
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPNfundo10 = new javax.swing.JPanel();
        JPNlista10 = new javax.swing.JPanel();
        JLBlista10 = new javax.swing.JLabel();
        JSPtabela10 = new javax.swing.JScrollPane();
        JTBtabela10 = new javax.swing.JTable();
        JTBatualizar10 = new javax.swing.JButton();
        JTBvoltar10 = new javax.swing.JButton();
        JPNtabelaencomenda10 = new javax.swing.JPanel();
        JLBtabelaencomenda10 = new javax.swing.JLabel();
        JLBmotoconnect10 = new javax.swing.JLabel();
        JTFnumero10 = new javax.swing.JTextField();
        JTFdata10 = new javax.swing.JTextField();
        JTFstatus10 = new javax.swing.JTextField();
        JLBnumero10 = new javax.swing.JLabel();
        JLBdata10 = new javax.swing.JLabel();
        JLBstatus10 = new javax.swing.JLabel();
        JTBexcluir10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPNfundo10.setBackground(new java.awt.Color(0, 0, 204));
        JPNfundo10.setPreferredSize(new java.awt.Dimension(1000, 600));

        JPNlista10.setBackground(new java.awt.Color(0, 102, 255));
        JPNlista10.setPreferredSize(new java.awt.Dimension(844, 30));

        JLBlista10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLBlista10.setForeground(new java.awt.Color(255, 255, 255));
        JLBlista10.setText("Lista de encomendas");

        javax.swing.GroupLayout JPNlista10Layout = new javax.swing.GroupLayout(JPNlista10);
        JPNlista10.setLayout(JPNlista10Layout);
        JPNlista10Layout.setHorizontalGroup(
            JPNlista10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNlista10Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(JLBlista10)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        JPNlista10Layout.setVerticalGroup(
            JPNlista10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNlista10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBlista10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        JTBtabela10.setBackground(new java.awt.Color(255, 51, 51));
        JTBtabela10.setForeground(new java.awt.Color(255, 255, 255));
        JTBtabela10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "numero_pedido", "cidade_origem", "nome", "cidade_destino", "data_entrega", "statuss"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTBtabela10.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JTBtabela10AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        JSPtabela10.setViewportView(JTBtabela10);

        JTBatualizar10.setBackground(new java.awt.Color(255, 51, 51));
        JTBatualizar10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JTBatualizar10.setForeground(new java.awt.Color(255, 255, 255));
        JTBatualizar10.setText("ATUALIZAR STATUS");
        JTBatualizar10.setMaximumSize(new java.awt.Dimension(106, 25));
        JTBatualizar10.setPreferredSize(new java.awt.Dimension(106, 25));
        JTBatualizar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBatualizar10ActionPerformed(evt);
            }
        });

        JTBvoltar10.setBackground(new java.awt.Color(255, 51, 51));
        JTBvoltar10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JTBvoltar10.setForeground(new java.awt.Color(255, 255, 255));
        JTBvoltar10.setText("VOLTAR");
        JTBvoltar10.setMaximumSize(new java.awt.Dimension(106, 25));
        JTBvoltar10.setPreferredSize(new java.awt.Dimension(106, 25));
        JTBvoltar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBvoltar10ActionPerformed(evt);
            }
        });

        JPNtabelaencomenda10.setBackground(new java.awt.Color(255, 0, 51));

        JLBtabelaencomenda10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLBtabelaencomenda10.setForeground(new java.awt.Color(255, 255, 255));
        JLBtabelaencomenda10.setText("Tabela encomendas");

        javax.swing.GroupLayout JPNtabelaencomenda10Layout = new javax.swing.GroupLayout(JPNtabelaencomenda10);
        JPNtabelaencomenda10.setLayout(JPNtabelaencomenda10Layout);
        JPNtabelaencomenda10Layout.setHorizontalGroup(
            JPNtabelaencomenda10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNtabelaencomenda10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBtabelaencomenda10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPNtabelaencomenda10Layout.setVerticalGroup(
            JPNtabelaencomenda10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNtabelaencomenda10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBtabelaencomenda10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JLBmotoconnect10.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\MotoConnect_Projeto\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\motoqueiro.png")); // NOI18N

        JTFnumero10.setBackground(new java.awt.Color(204, 204, 204));

        JTFdata10.setBackground(new java.awt.Color(204, 204, 204));

        JTFstatus10.setBackground(new java.awt.Color(204, 204, 204));

        JLBnumero10.setForeground(new java.awt.Color(255, 255, 255));
        JLBnumero10.setText("Numero do pedido:");

        JLBdata10.setForeground(new java.awt.Color(255, 255, 255));
        JLBdata10.setText("Data de entrega:");

        JLBstatus10.setForeground(new java.awt.Color(255, 255, 255));
        JLBstatus10.setText("Status:");

        JTBexcluir10.setBackground(new java.awt.Color(255, 51, 51));
        JTBexcluir10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JTBexcluir10.setForeground(new java.awt.Color(255, 255, 255));
        JTBexcluir10.setText("EXCLUIR");
        JTBexcluir10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBexcluir10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPNfundo10Layout = new javax.swing.GroupLayout(JPNfundo10);
        JPNfundo10.setLayout(JPNfundo10Layout);
        JPNfundo10Layout.setHorizontalGroup(
            JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNfundo10Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNfundo10Layout.createSequentialGroup()
                        .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JPNfundo10Layout.createSequentialGroup()
                                .addComponent(JTBatualizar10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JTBexcluir10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTBvoltar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JPNtabelaencomenda10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(JPNfundo10Layout.createSequentialGroup()
                                .addComponent(JLBmotoconnect10, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JPNlista10, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JSPtabela10, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(173, 173, 173))
                    .addGroup(JPNfundo10Layout.createSequentialGroup()
                        .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLBnumero10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTFnumero10))
                        .addGap(46, 46, 46)
                        .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFdata10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLBdata10))
                        .addGap(31, 31, 31)
                        .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLBstatus10)
                            .addComponent(JTFstatus10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        JPNfundo10Layout.setVerticalGroup(
            JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNfundo10Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPNlista10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBmotoconnect10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(JPNtabelaencomenda10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JSPtabela10, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBnumero10)
                    .addComponent(JLBdata10)
                    .addComponent(JLBstatus10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFnumero10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFdata10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFstatus10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTBatualizar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTBvoltar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTBexcluir10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNfundo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNfundo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTBvoltar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBvoltar10ActionPerformed
        this.dispose();
        Tela_Menu JBTvoltar10 = new Tela_Menu();
        JBTvoltar10.setVisible(true);
    }//GEN-LAST:event_JTBvoltar10ActionPerformed

    private void JTBtabela10AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JTBtabela10AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_JTBtabela10AncestorAdded

    private void JTBatualizar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBatualizar10ActionPerformed
     atualizarTabela();
    }//GEN-LAST:event_JTBatualizar10ActionPerformed

    private void JTBexcluir10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBexcluir10ActionPerformed
    // Chamada do método para excluir um pedido
        excluirPedido();
    }//GEN-LAST:event_JTBexcluir10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Lista_Encomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Lista_Encomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Lista_Encomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Lista_Encomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Lista_Encomendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLBdata10;
    private javax.swing.JLabel JLBlista10;
    private javax.swing.JLabel JLBmotoconnect10;
    private javax.swing.JLabel JLBnumero10;
    private javax.swing.JLabel JLBstatus10;
    private javax.swing.JLabel JLBtabelaencomenda10;
    private javax.swing.JPanel JPNfundo10;
    private javax.swing.JPanel JPNlista10;
    private javax.swing.JPanel JPNtabelaencomenda10;
    private javax.swing.JScrollPane JSPtabela10;
    private javax.swing.JButton JTBatualizar10;
    private javax.swing.JButton JTBexcluir10;
    private javax.swing.JTable JTBtabela10;
    private javax.swing.JButton JTBvoltar10;
    private javax.swing.JTextField JTFdata10;
    private javax.swing.JTextField JTFnumero10;
    private javax.swing.JTextField JTFstatus10;
    // End of variables declaration//GEN-END:variables
}
