/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motoconnect;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Tela_Lista_Encomendas extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Lista_Encomendas
     */
    public Tela_Lista_Encomendas() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPNfundo10 = new javax.swing.JPanel();
        JPNlista10 = new javax.swing.JPanel();
        JLBlista10 = new javax.swing.JLabel();
        JSPtabela10 = new javax.swing.JScrollPane();
        JTBtabela10 = new javax.swing.JTable();
        JTBatualizar10 = new javax.swing.JButton();
        JTBvoltar10 = new javax.swing.JButton();
        JPNtabelaencomenda10 = new javax.swing.JPanel();
        JLBtabelaencomenda10 = new javax.swing.JLabel();
        JLBmotoconnect10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPNfundo10.setBackground(new java.awt.Color(0, 0, 204));
        JPNfundo10.setPreferredSize(new java.awt.Dimension(1000, 600));

        JPNlista10.setBackground(new java.awt.Color(0, 102, 255));
        JPNlista10.setPreferredSize(new java.awt.Dimension(844, 30));

        JLBlista10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLBlista10.setForeground(new java.awt.Color(255, 255, 255));
        JLBlista10.setText("Lista de encomendas");

        javax.swing.GroupLayout JPNlista10Layout = new javax.swing.GroupLayout(JPNlista10);
        JPNlista10.setLayout(JPNlista10Layout);
        JPNlista10Layout.setHorizontalGroup(
            JPNlista10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNlista10Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(JLBlista10)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        JPNlista10Layout.setVerticalGroup(
            JPNlista10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNlista10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBlista10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        JTBtabela10.setBackground(new java.awt.Color(255, 51, 51));
        JTBtabela10.setForeground(new java.awt.Color(255, 255, 255));
        JTBtabela10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12345", "Rua das Flores, 123, Jardim da Penha, Vitória", " Vitor Ramos", "Rua das Palmeiras, 123 - Centro, Vitória", "03/05/24", "Em andamento"},
                {"12346", "Avenida Central, 456, Praia do Canto, Vitória", "Gabriel Antõnio", "Avenida Champagnat, 456 - Praia da Costa, Vila Velha", "04/05/24", "Agendada"},
                {"12347", "Travessa do Sol, 789, Centro, Vila Velha", "Melissa Lopes", "Travessa das Flores, 789 - Jardim América, Cariacica", "02/05/24", "Finalizada"},
                {"12348", "Rua dos Pássaros, 321, Itapuã, Vila Velha", "Tais Silva", "Avenida Tal, 321 - Serra Dourada, Serra", "02/05/24", "Finalizada"},
                {"12349", "Avenida Beira Mar, 654, Praia da Costa, Vila Velha", "Ramon Cardoso", "Praça Principal, 101 - Centro, Viana", "03/05/24", "Em andamento"},
                {"12350", "Rua do Comércio, 987, Centro, Serra", "Paolo Gimenez", "Rua dos Coqueiros, 234 - Jardim Camburi, Vitória", "03/05/24", "Em andamento"},
                {"12351", "Avenida das Indústrias, 135, Civit II, Serra", "Ygor Pereira", "Avenida das Gaivotas, 567 - Itapuã, Vila Velha ", "02/05/24", "Finalizada"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero do pedido", "Endereço de origem", "Entregador", "Endereço do destino", "Data de entrega", "Status"
            }
        ));
        JTBtabela10.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JTBtabela10AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        JSPtabela10.setViewportView(JTBtabela10);

        JTBatualizar10.setBackground(new java.awt.Color(255, 51, 51));
        JTBatualizar10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JTBatualizar10.setForeground(new java.awt.Color(255, 255, 255));
        JTBatualizar10.setText("ATUALIZAR STATUS");
        JTBatualizar10.setMaximumSize(new java.awt.Dimension(106, 25));
        JTBatualizar10.setPreferredSize(new java.awt.Dimension(106, 25));
        JTBatualizar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBatualizar10ActionPerformed(evt);
            }
        });

        JTBvoltar10.setBackground(new java.awt.Color(255, 51, 51));
        JTBvoltar10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JTBvoltar10.setForeground(new java.awt.Color(255, 255, 255));
        JTBvoltar10.setText("VOLTAR");
        JTBvoltar10.setMaximumSize(new java.awt.Dimension(106, 25));
        JTBvoltar10.setPreferredSize(new java.awt.Dimension(106, 25));
        JTBvoltar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBvoltar10ActionPerformed(evt);
            }
        });

        JPNtabelaencomenda10.setBackground(new java.awt.Color(255, 0, 51));

        JLBtabelaencomenda10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLBtabelaencomenda10.setForeground(new java.awt.Color(255, 255, 255));
        JLBtabelaencomenda10.setText("Tabela encomendas");

        javax.swing.GroupLayout JPNtabelaencomenda10Layout = new javax.swing.GroupLayout(JPNtabelaencomenda10);
        JPNtabelaencomenda10.setLayout(JPNtabelaencomenda10Layout);
        JPNtabelaencomenda10Layout.setHorizontalGroup(
            JPNtabelaencomenda10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNtabelaencomenda10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBtabelaencomenda10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPNtabelaencomenda10Layout.setVerticalGroup(
            JPNtabelaencomenda10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNtabelaencomenda10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBtabelaencomenda10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JLBmotoconnect10.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\MotoConnect_Projeto\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\motoqueiro.png")); // NOI18N

        javax.swing.GroupLayout JPNfundo10Layout = new javax.swing.GroupLayout(JPNfundo10);
        JPNfundo10.setLayout(JPNfundo10Layout);
        JPNfundo10Layout.setHorizontalGroup(
            JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNfundo10Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPNfundo10Layout.createSequentialGroup()
                        .addComponent(JTBatualizar10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTBvoltar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JPNtabelaencomenda10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JPNfundo10Layout.createSequentialGroup()
                        .addComponent(JLBmotoconnect10, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JPNlista10, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JSPtabela10, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(173, 173, 173))
        );
        JPNfundo10Layout.setVerticalGroup(
            JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNfundo10Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPNlista10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLBmotoconnect10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(JPNtabelaencomenda10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JSPtabela10, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addGroup(JPNfundo10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTBatualizar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTBvoltar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNfundo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNfundo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTBvoltar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBvoltar10ActionPerformed
        // TODO add your handling code here:
        Tela_Lista_Encomendas.this.dispose();
        Tela_Menu JBTvoltar10 = new Tela_Menu();
        JBTvoltar10.setVisible(true);
    }//GEN-LAST:event_JTBvoltar10ActionPerformed

    private void JTBtabela10AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JTBtabela10AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_JTBtabela10AncestorAdded

    private void JTBatualizar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBatualizar10ActionPerformed
        
    
    }//GEN-LAST:event_JTBatualizar10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Lista_Encomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Lista_Encomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Lista_Encomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Lista_Encomendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Lista_Encomendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLBlista10;
    private javax.swing.JLabel JLBmotoconnect10;
    private javax.swing.JLabel JLBtabelaencomenda10;
    private javax.swing.JPanel JPNfundo10;
    private javax.swing.JPanel JPNlista10;
    private javax.swing.JPanel JPNtabelaencomenda10;
    private javax.swing.JScrollPane JSPtabela10;
    private javax.swing.JButton JTBatualizar10;
    private javax.swing.JTable JTBtabela10;
    private javax.swing.JButton JTBvoltar10;
    // End of variables declaration//GEN-END:variables
}
