/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motoconnect;

/**
 *
 * @author PC
 */
public class Tela_Menu extends javax.swing.JFrame {

    /**
     * Creates new form MotoConnect_Menu
     */
    public Tela_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPNazulescuro2 = new javax.swing.JPanel();
        JBTcadastrodefubcionario2 = new javax.swing.JButton();
        JBTregistrocalculodefrete2 = new javax.swing.JButton();
        JBTobservacoesecomentarios2 = new javax.swing.JButton();
        JBTalertas2 = new javax.swing.JButton();
        JBTcadastrodecliente2 = new javax.swing.JButton();
        JPNusuario2 = new javax.swing.JPanel();
        JLBbemvindo2 = new javax.swing.JLabel();
        JTFusuario2 = new javax.swing.JTextField();
        JLBmotoconnect2 = new javax.swing.JLabel();
        JTBlistaencomendas2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JLBparavermelha2 = new javax.swing.JPanel();
        JLBcadastrodefuncionario2 = new javax.swing.JLabel();
        JLBregistrodecalculofrete2 = new javax.swing.JLabel();
        JLBcadastrodecliente2 = new javax.swing.JLabel();
        JLBobservacoesecomentarios2 = new javax.swing.JLabel();
        JLBlistaencomenda2 = new javax.swing.JLabel();
        JLBalertas2 = new javax.swing.JLabel();
        JLBsair2 = new javax.swing.JLabel();
        JBTsair2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPNazulescuro2.setBackground(new java.awt.Color(0, 51, 204));
        JPNazulescuro2.setPreferredSize(new java.awt.Dimension(1000, 600));
        JPNazulescuro2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBTcadastrodefubcionario2.setIcon(new javax.swing.ImageIcon("D:\\Users\\grpereira\\Desktop\\Giampaolo_Projeto_TechNight\\Giampaolo_Projeto_Technight\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\Cadastro de Funcionario.png")); // NOI18N
        JBTcadastrodefubcionario2.setContentAreaFilled(false);
        JBTcadastrodefubcionario2.setMaximumSize(new java.awt.Dimension(50, 50));
        JBTcadastrodefubcionario2.setMinimumSize(new java.awt.Dimension(0, 0));
        JBTcadastrodefubcionario2.setPreferredSize(new java.awt.Dimension(50, 50));
        JBTcadastrodefubcionario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTcadastrodefubcionario2ActionPerformed(evt);
            }
        });
        JPNazulescuro2.add(JBTcadastrodefubcionario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 50, 50));

        JBTregistrocalculodefrete2.setIcon(new javax.swing.ImageIcon("D:\\Users\\grpereira\\Desktop\\Giampaolo_Projeto_TechNight\\Giampaolo_Projeto_Technight\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\Calculo de frete.png")); // NOI18N
        JBTregistrocalculodefrete2.setContentAreaFilled(false);
        JBTregistrocalculodefrete2.setMaximumSize(new java.awt.Dimension(50, 50));
        JBTregistrocalculodefrete2.setMinimumSize(new java.awt.Dimension(50, 50));
        JBTregistrocalculodefrete2.setPreferredSize(new java.awt.Dimension(50, 50));
        JBTregistrocalculodefrete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTregistrocalculodefrete2ActionPerformed(evt);
            }
        });
        JPNazulescuro2.add(JBTregistrocalculodefrete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 50, 50));

        JBTobservacoesecomentarios2.setIcon(new javax.swing.ImageIcon("D:\\Users\\grpereira\\Desktop\\Giampaolo_Projeto_TechNight\\Giampaolo_Projeto_Technight\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\Observações e Comentarios.png")); // NOI18N
        JBTobservacoesecomentarios2.setContentAreaFilled(false);
        JBTobservacoesecomentarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTobservacoesecomentarios2ActionPerformed(evt);
            }
        });
        JPNazulescuro2.add(JBTobservacoesecomentarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 50, 50));

        JBTalertas2.setIcon(new javax.swing.ImageIcon("D:\\Users\\grpereira\\Desktop\\Giampaolo_Projeto_TechNight\\Giampaolo_Projeto_Technight\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\Alertas.png")); // NOI18N
        JBTalertas2.setContentAreaFilled(false);
        JBTalertas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTalertas2ActionPerformed(evt);
            }
        });
        JPNazulescuro2.add(JBTalertas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 50, 50));

        JBTcadastrodecliente2.setIcon(new javax.swing.ImageIcon("D:\\Users\\grpereira\\Desktop\\Giampaolo_Projeto_TechNight\\Giampaolo_Projeto_Technight\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\Cadastro de Cliente.png")); // NOI18N
        JBTcadastrodecliente2.setContentAreaFilled(false);
        JBTcadastrodecliente2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBTcadastrodecliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTcadastrodecliente2ActionPerformed(evt);
            }
        });
        JPNazulescuro2.add(JBTcadastrodecliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 50, 50));

        JPNusuario2.setBackground(new java.awt.Color(0, 102, 255));

        JLBbemvindo2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLBbemvindo2.setForeground(new java.awt.Color(255, 255, 255));
        JLBbemvindo2.setText("Bem vindo !");

        JTFusuario2.setBackground(new java.awt.Color(0, 102, 255));
        JTFusuario2.setForeground(new java.awt.Color(255, 255, 255));
        JTFusuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFusuario2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPNusuario2Layout = new javax.swing.GroupLayout(JPNusuario2);
        JPNusuario2.setLayout(JPNusuario2Layout);
        JPNusuario2Layout.setHorizontalGroup(
            JPNusuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNusuario2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JLBbemvindo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFusuario2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPNusuario2Layout.setVerticalGroup(
            JPNusuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNusuario2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(JPNusuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBbemvindo2)
                    .addComponent(JTFusuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        JPNazulescuro2.add(JPNusuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 300, 60));
        JPNazulescuro2.add(JLBmotoconnect2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 110));

        JTBlistaencomendas2.setIcon(new javax.swing.ImageIcon("D:\\Users\\grpereira\\Desktop\\Giampaolo_Projeto_TechNight\\Giampaolo_Projeto_Technight\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\5-removebg-preview (1).png")); // NOI18N
        JTBlistaencomendas2.setContentAreaFilled(false);
        JTBlistaencomendas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBlistaencomendas2ActionPerformed(evt);
            }
        });
        JPNazulescuro2.add(JTBlistaencomendas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Users\\grpereira\\Desktop\\Giampaolo_Projeto_TechNight\\Giampaolo_Projeto_Technight\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\motoqueiro.png")); // NOI18N
        JPNazulescuro2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 240, 120));

        JLBparavermelha2.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout JLBparavermelha2Layout = new javax.swing.GroupLayout(JLBparavermelha2);
        JLBparavermelha2.setLayout(JLBparavermelha2Layout);
        JLBparavermelha2Layout.setHorizontalGroup(
            JLBparavermelha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        JLBparavermelha2Layout.setVerticalGroup(
            JLBparavermelha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        JPNazulescuro2.add(JLBparavermelha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1000, 20));
        JPNazulescuro2.add(JLBcadastrodefuncionario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));
        JPNazulescuro2.add(JLBregistrodecalculofrete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));
        JPNazulescuro2.add(JLBcadastrodecliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));
        JPNazulescuro2.add(JLBobservacoesecomentarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 50, 60));
        JPNazulescuro2.add(JLBlistaencomenda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));
        JPNazulescuro2.add(JLBalertas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        JLBsair2.setIcon(new javax.swing.ImageIcon("D:\\Users\\grpereira\\Desktop\\Giampaolo_Projeto_TechNight\\Giampaolo_Projeto_Technight\\Giampaolo_Projeto_Technight\\MotoConnect\\src\\main\\java\\imagem_login\\Sair.png")); // NOI18N
        JPNazulescuro2.add(JLBsair2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, 50, 60));

        JBTsair2.setContentAreaFilled(false);
        JBTsair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTsair2ActionPerformed(evt);
            }
        });
        JPNazulescuro2.add(JBTsair2, new org.netbeans.lib.awtextra.AbsoluteConstraints(892, 490, 50, 60));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastro ");
        JPNazulescuro2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Funcionario");
        JPNazulescuro2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("  Frete");
        JPNazulescuro2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Calculo");
        JPNazulescuro2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cadastro");
        JPNazulescuro2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Cliente");
        JPNazulescuro2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lista de");
        JPNazulescuro2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Encomendas");
        JPNazulescuro2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Observações e");
        JPNazulescuro2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" Alertas");
        JPNazulescuro2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Comentarios");
        JPNazulescuro2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SAIR");
        JPNazulescuro2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 550, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" Aviso Importante: Entregas Disponíveis Apenas na Região da Grande Vitória ");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Informamos que nosso serviço de entrega está restrito à região da Grande Vitória. Não");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("estamos realizando entregas fora desta área no momento. Pedimos a compreensão dos");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("clientes e reforçamos nosso compromisso em oferecer o melhor atendimento possível");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("dentro da nossa região de atuação, abrangendo os municípios de Vitória, Vila Velha,");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Cariacica, Serra e Viana. Agradecemos pela compreensão e pela preferência.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel14))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel19)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        JPNazulescuro2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 510, 190));

        getContentPane().add(JPNazulescuro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTcadastrodefubcionario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTcadastrodefubcionario2ActionPerformed
        // TODO add your handling code here:
        Tela_Menu.this.dispose();
        Tela_Cadastro_Funcionario JBTcadastrodefuncionario2 = new Tela_Cadastro_Funcionario();
        JBTcadastrodefuncionario2.setVisible(true);
    }//GEN-LAST:event_JBTcadastrodefubcionario2ActionPerformed

    private void JBTregistrocalculodefrete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTregistrocalculodefrete2ActionPerformed
        // TODO add your handling code here:
        Tela_Menu.this.dispose();
        Tela_Tipo_Carga JBTregistrocalculodefrete2 = new Tela_Tipo_Carga();
        JBTregistrocalculodefrete2.setVisible(true);
    }//GEN-LAST:event_JBTregistrocalculodefrete2ActionPerformed

    private void JBTcadastrodecliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTcadastrodecliente2ActionPerformed
        // TODO add your handling code here:
        Tela_Menu.this.dispose();
        Tela_Cadastro_Cliente JBTcadastrodecliente2 = new Tela_Cadastro_Cliente();
        JBTcadastrodecliente2.setVisible(true);
    }//GEN-LAST:event_JBTcadastrodecliente2ActionPerformed

    private void JBTobservacoesecomentarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTobservacoesecomentarios2ActionPerformed
        // TODO add your handling code here:
        Tela_Menu.this.dispose();
        Tela_Observacoes_Comentarioes JBTobservacoesecomentarios2 = new Tela_Observacoes_Comentarioes();
        JBTobservacoesecomentarios2.setVisible(true);
    }//GEN-LAST:event_JBTobservacoesecomentarios2ActionPerformed

    private void JTBlistaencomendas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBlistaencomendas2ActionPerformed
        // TODO add your handling code here:
        Tela_Menu.this.dispose();
        Tela_Lista_Encomendas JTBlistaencomendas2 = new Tela_Lista_Encomendas();
        JTBlistaencomendas2.setVisible(true);
    }//GEN-LAST:event_JTBlistaencomendas2ActionPerformed

    private void JBTsair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTsair2ActionPerformed
        // TODO add your handling code here:
        Tela_Menu.this.dispose();
        Tela_Login JBTsair2 = new Tela_Login();
        JBTsair2.setVisible(true);
    }//GEN-LAST:event_JBTsair2ActionPerformed

    private void JTFusuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFusuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFusuario2ActionPerformed

    private void JBTalertas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTalertas2ActionPerformed
        Tela_Menu.this.dispose();
        Tela_Alertas JBTalertas2 = new Tela_Alertas();
        JBTalertas2.setVisible(true);
    }//GEN-LAST:event_JBTalertas2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTalertas2;
    private javax.swing.JButton JBTcadastrodecliente2;
    private javax.swing.JButton JBTcadastrodefubcionario2;
    private javax.swing.JButton JBTobservacoesecomentarios2;
    private javax.swing.JButton JBTregistrocalculodefrete2;
    private javax.swing.JButton JBTsair2;
    private javax.swing.JLabel JLBalertas2;
    private javax.swing.JLabel JLBbemvindo2;
    private javax.swing.JLabel JLBcadastrodecliente2;
    private javax.swing.JLabel JLBcadastrodefuncionario2;
    private javax.swing.JLabel JLBlistaencomenda2;
    private javax.swing.JLabel JLBmotoconnect2;
    private javax.swing.JLabel JLBobservacoesecomentarios2;
    private javax.swing.JPanel JLBparavermelha2;
    private javax.swing.JLabel JLBregistrodecalculofrete2;
    private javax.swing.JLabel JLBsair2;
    private javax.swing.JPanel JPNazulescuro2;
    private javax.swing.JPanel JPNusuario2;
    private javax.swing.JButton JTBlistaencomendas2;
    private javax.swing.JTextField JTFusuario2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
